version: '3.1'

services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  oracle_db:
    image: store/oracle/database-enterprise:12.2.0.1
    environment:
      ORACLE_PWD: password
      ORACLE_PDB: example_db
    ports:
      - 1521:1521
  redis_db:
    image: redis
    ports:
      - 6379:6379
